#!/bin/bash

cd /home/pi/
#copy originals into 64GB flash drive mounted to a directory in /home/pi/photobooth_backup
cp temp/snap* /home/pi/photobooth_backup/photobooth_images/

#resize photos to 570x380
mogrify -resize 570x380 /home/pi/temp/*.jpg

#arrange four photos into vertical 1x4 table
montage /home/pi/temp/*.jpg -tile 1x4 -geometry +10+10 /home/pi/temp/temp_montage2.jpg

#arrange strip into side by side copy
montage /home/pi/temp/temp_montage2.jpg /home/pi/temp/temp_montage2.jpg -tile 2x1 -geometry +5+5 /home/pi/temp/temp_montage3.jpg

#add the photobooth logo under both strips
montage /home/pi/temp/temp_montage3.jpg /home/pi/photobooth_label.jpg -tile 1x2 -geometry +0+0 /home/pi/temp/temp_montage4.jpg

#add white space to strip
convert /home/pi/temp/temp_montage4.jpg -gravity center -extent 1272x1908 /home/pi/temp/temp_montage5.jpg

#send print job via CUPS
lp /home/pi/temp/temp_montage5.jpg

#create copy of strip for reprint command
cp /home/pi/temp/temp_montage5.jpg /home/pi/reprint.jpg

#upload photos to Google Drive
for (( i = 1; i <= 4; i++))
do
        sudo python /home/pi/scripts/photobooth/upload.py temp/snap_$i*
done

#archive strip
suffix=$(date +%Y-%m-%d_%H%M%S)
cp /home/pi/temp/temp_montage4.jpg /home/pi/photobooth_backup/PB_archive/PB_${suffix}.jpg
cp /home/pi/temp/temp_montage4.jpg /home/pi/temp/PB_${suffix}.jpg
sudo python /home/pi/scripts/photobooth/upload.py temp/PB_${suffix}*

#cleanup
rm /home/pi/temp/*.jpg
